sudo: required
language: java
dist: trusty
jdk: openjdk8
 
services:
  - docker
   
script:
- ./mvnw clean package
- ./mvnw dockerfile:build

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=chejerlakarthik/ckboot-contacts-app
- docker build -t $IMAGE_NAME:$TAG .
- docker push $IMAGE_NAME