sudo: required
language: java
dist: trusty
jdk: openjdk8

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get install python3
- python3 --version

env:
  global:
  - secure: iG6VRNo9Ka2Y4iPc9YsMSICoVDZQ8GAwE3vAXm7ojkOulay5FZLQtozYz/+TAcnPs30+zJyc8urMuy3fQo9CgaRMx6O2t7sV6qirOdwTNZyNToKNwILaLTPAh+z26PXMQPF13H4/EZmqPAkPyixuTr/r1aacX9Ud5Hj1HFZHlzCQ1oAk4LkNHCrzZUdDmct125kIWf3XQUQMHxMXnqUluKRkglq86L/Xj5Z1Nkvb5+CqaATvh1svobwfy7Rs5OCAVvbi4Q2s+lA0Gq4es5TfaUlXnUYNwMOqeJ1IMPJp4an8F0EliS1U7rsKsDlPaHjhD3107q+cHIosb+draC7BaDS4mBmdY4v5xgh8qb4UOkS/Lwy2f1GhxN8XEolXhS6pmRXyRWh0e9/ThngSl1E/Ugx3E8T/rlzr7SlCDNGjz5PgjPHTEE5ZEyQbbi64FPwfjR45/3lRON5335u4zG1MBzMW8vJOw/3TaVyDwOIypZwkNlDIa7oRo9igZ1viJnPPoGZrEQpd2U6G6iX8sdbEqwnwU7Yd9xoovrfn94LSsCpfC4Oxoh9gUNzJ05mC+DRnT84ILNaWJOiaOu28jHwRiwXtERUnjP2QoaKCrUZfHeZTzInI4H+hI2Mf/F8KjKv6mmdiydIOpXDm8VRURPcTzGxGIn4DFG8V3Mezhf9wDg4=
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: chejerlakarthik-github
    token:
      secure: "$SONAR_TOKEN"

script:
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=chejerlakarthik_contacts-app"
- "./mvnw clean package"

after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=chejerlakarthik/contacts-app
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $IMAGE_NAME:$TAG

before_deploy:
- python3 generateConfig.py MONGO_USER=$MONGO_USER,MONGO_PASSWORD=$MONGO_PASSWORD,SERVER_PORT=$LB_PORT $ZIPFILE_NAME

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  zip_file: "$ZIPFILE_NAME"
  region: ap-southeast-1
  app: ebs-contacts-app
  env: EbsContactsApp-env
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET"
  bucket_name: elasticbeanstalk-ap-southeast-1-035765131789
  bucket_path: ebs-contacts-app
  on:
    branch: master